name: Sync Obsidian Posts

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes
  workflow_dispatch:

jobs:
  sync-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blog repo
        uses: actions/checkout@v4
        with:
          path: blog

      - name: Checkout vault repo
        uses: actions/checkout@v4
        with:
          repository: <your-obsidian-vault-owner>/<your-obsidian-vault-repo>
          token: ${{ secrets.VAULT_REPO_TOKEN }}
          path: vault

      - name: Sync markdown files
        run: |
          rsync -av --delete vault/posts/ blog/posts/

      - name: Generate index.json
        run: |
          cd blog
          python3 scripts/generate_index.py

      - name: Commit and push if changes
        run: |
          cd blog
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/ index.json
          git diff --cached --quiet || git commit -m "Sync posts from vault and update index.json"
          git push